export const bgs = {
  home: "photo3.jpg",
  about: "photo2.jpg",
  contact: "photo1.jpg",
  areas: "photo5.jpg",
  login: "photo3.jpg",
  build: "photo9.jpg",
  vision: "photo1.jpg",
  community: "slides/community.jpg",
  sustainability: "slides/sustainability.png",
  construction: "slides/construction.png",
  investment: "slides/investment.png",
  common: "slides/common.png",
  sand: "slides/sand.png",
  map: "slides/map.png",
  land: "slides/land.png",
  size: "slides/size.png",
  ventanilla: "slides/ventanilla.png",
  404: "photo3.jpg",
  500: "photo3.jpg",
  admin: "photo3.jpg",
  values: "photo3.jpg",
};
